name: Haskell CI

on: [push]

jobs:
  build:
   
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup nix
      run: |
        curl https://nixos.org/nix/install | sh
    - name: Setup cachix
      run: |
        . /Users/runner/.nix-profile/etc/profile.d/nix.sh
        bash <(curl https://nixos.org/nix/install)
    - name: Build
      run: |
        . /Users/runner/.nix-profile/etc/profile.d/nix.sh
        nix-build
